---
output: html_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

<div style="text-align: justify"> 

# Umfragemethodik {- #methodik}

```{r, include=FALSE}
source("source.R")
```

Hier werden die Hauptaspekte der Erhebungsmethodik für alle 49 an der Charité gestellten Fragen erläutert. Details gemäß dem Leitfaden zur transparenten Erhebungsdokumentation werden separat veröffentlicht. Die Methodik und Ergebnisse zu den zehn Fragen, die bei der FDM-Bedarfserhebung der Berlin University Alliance (BUA) institutionsübergreifend gestellt wurden, sind [in einem separaten Bericht](https://zenodo.org/communities/bua-fdm/) beschrieben.

## Zielsetzung und Studiendesign {-}

Ziel der umfragebasierten Bedarfserhebung an der Charité war es vor allem, aktuelle Praktiken und Bedarfe im FDM festzustellen. Darüber hinaus wurden Fragen zu Motivation und Einstellungen, Inanspruchnahme von Dienstleistungen und Kenntnissen zu bestehenden Regelungen und Anreizmaßnahmen gestellt. 

Der Fragebogen enthielt 49 Fragen (39 ausschließlich an der Charité und 10 BUA-übergreifend), wobei es sich sowohl um geschlossene Fragen (Einzel- und Mehrfach-Auswahl sowie Matrix- Fragen) als auch um offene Fragen handelte. Geschlossene Fragen ermöglichten es den Teilnehmenden, vordefinierte Aussagen zu bewerten, und offene Fragen ermöglichten es ihnen, ihre Meinung zu äußern oder eine alternative Antwort auf die geschlossenen Fragen zu geben (unter z.B. "Sonstiges, und zwar"). Die Befragung wurde in englischer und deutscher Sprache mit der Software Sociolutions QUAMP, Modul qSurveyor8 durchgeführt. Dieses Tool unterstützte die Implementierung von Fragen, die Kodierung von Datensätzen sowie die Speicherung von Daten (Umfrageteilnahmestatistiken auf Sociolutions-Servern und Umfrageergebnisse auf institutionellen Servern).

Keine der Fragen war obligatorisch. Ein Teil der Fragen wurde den Teilnehmenden mit Hilfe von Filterfragen basierend auf ihren bereits gegebenen Antworten selektiv präsentiert. So wurden beispielsweise Fragen zu Datenmanagementplänen (DMP) nur Teilnehmenden angezeigt, die zuvor mindestens einmal einen DMP verfasst hatten. Infolgedessen wurden keinem/keiner der Teilnehmenden alle 49 Fragen vorgelegt, im Durchschnitt erhielten Teilnehmende 37 Fragen.

## Zielgruppe, Stichprobe und Dissemination {-}

Die Befragung richtete sich an alle Mitarbeitenden der Charité, die zum Befragungszeitpunkt mit Forschungsdaten gearbeitet haben. Die Stichprobenerhebung erfolgte durch den Versand personalisierter E-Mails an die folgenden drei Gruppen: (i) in FACTscience (Institutionelles Forschungsinformationssystem der Charité) gelistete Mitarbeitende der Charité, (ii) wissenschaftliche Mitarbeitende des BIH und (iii) medizinische Doktorand*innen der Charité. Am 7. Dezember 2021 wurden insgesamt 8545 Einladungs-E-Mails zur Umfrage verschickt. Diese E-Mails enthielten eine Erläuterung des Zwecks der Umfrage, einen Link zur Teilnahme, Datenschutzinformationen und einen Link für Teilnehmende, die nicht mit Forschungsdaten arbeiteten, um ihre E-Mail-Adresse aus der Umfrage-E-Mail-Liste zu entfernen. Die übrigen Teilnehmenden erhielten bis zu drei weitere Erinnerungsmails (20.12.2021, 05.01.2022 und 12.01.2022), in denen die Frist für die Teilnahme an der Befragung mitgeteilt wurde (19.01.2022). Die institutionelle Umfrage wurde auch über Kanäle der BUA kommuniziert. Teilnehmende, die angaben, nicht mit digitalen Forschungsdaten zu arbeiten, wurden frühzeitig zur letzten Freitextfrage ans Ende des Fragebogens geleitet.

## Datenschutz und Informationssicherheit {-}

Die Befragung wurde mit Zustimmung der betrieblichen Datenschutzbeauftragten und des Betriebsrats durchgeführt. Um eine anonymisierte Datenerhebung zu gewährleisten, wurden zudem durch technische und organisatorische Maßnahmen personenbezogene Daten der Teilnehmenden (Name und E-Mail-Adresse) getrennt von den Befragungsdaten in QUAMP gespeichert. Eine Zusammenführung wäre im Erhebungszeitraum möglich gewesen, wenn Teilnehmende von ihren Rechten auf Berichtigung, Auskunft oder Löschung Gebrauch gemacht hätten, dieser Fall trat allerdings nicht ein. Nach Ablauf des Erhebungszeitraums wurde die Verbindung zwischen Erhebungsdaten und identifizierenden Daten unwiderruflich gelöscht, wonach die oben genannten Rechte nicht mehr bestanden. 

Die Teilnehmenden wurden in der ersten Frage der Umfrage um ihre Einwilligung in die Datenverarbeitung gebeten. Wurde diese nicht gegeben, wurden die Teilnehmende an das Ende der Umfrage geleitet (Frage 49), wo sie einen Kommentar abgeben konnten. Mit erteilter Einwilligung in die Datenverarbeitung gaben die Teilnehmenden ihr Einverständnis zur uneingeschränkten Veröffentlichung derjenigen Daten, die als nahezu anonym angesehen werden können. Entsprechend werden die Ergebnisse für geschlossene Fragen (quantitative Daten) [in Zenodo offen geteilt](https://doi.org/10.5281/zenodo.7061742). Im Gegensatz dazu werden die Ergebnisse offener Fragen, die Freitextantworten enthalten, nicht in Rohform veröffentlicht.

Die Einwilligung sah eine Bearbeitung der Freitextantworten vor, um einen Rückschluss auf Personen auszuschließen. Die Freitextantworten wurden hierfür kategorisiert und es wurden diese Kategorisierungen offen geteilt. Die Angaben unter "Sonstiges" wurden grundsätzlich beibehalten, aber dort, wo sie Informationen enthielten, die auf eine Person schließen lassen konnten oder die in Bezug auf die Institution insgesamt sensibel sein konnten, vor der Veröffentlichung anonymisiert.
Um die langfristige Nachvollziehbarkeit und institutionelle Nutzung zu gewährleisten, wurden alle Daten einschließlich der qualitativen Daten (Freitextantworten) datenschutzkonform auf institutionellen Servern gespeichert, während quantitative Rohdaten und analysierte Daten in [GitHub](https://github.com/quest-bih/bua-rdm-survey) und in [Zenodo](https://doi.org/10.5281/zenodo.7061742) archiviert und offen zugänglich sind.

## Datenverarbeitung und -auswertung {-}

Die Umfragedaten wurden aus der QUAMP-Software als .xlsx-Datei exportiert und zur Datenbereinigung und -analyse mit der statistischen Programmiersprache R Version 4.2.1 geladen. Die importierten Daten wurden dann gemäß dem [Tidy Data Framework](https://doi.org/10.18637/jss.v059.i10) in ein langes Format konvertiert, um sie mit dem Codebuch zu verknüpfen. Das Codebuch (eine .xlsx-Datei) wurde mit R importiert und zur Entschlüsselung der Antworten mit den Umfragedaten zusammengeführt. 

Die Qualität der Daten wurde von zwei Projektmitarbeitenden nach dem Vier-Augen-Prinzip geprüft. Dazu überprüfte eine Person mit Excel, ob die Filterfragen wie geplant funktioniert hatten und listete die gefundenen Fehler auf. Die zweite Person implementierte die Datenbereinigung für alle Filterfragen mit einem Filtersprung, wie im R-Code beschrieben. Dieser Datenbereinigungsschritt war für einige Filterfragen erforderlich, bei denen der Filter fehlschlug, wenn Teilnehmende die Browsernavigation im Fragebogen und nicht die in QUAMP implementierten Schaltflächen verwendeten.

In die hier vorgestellten Analysen sind diejenigen 471 Fragebögen eingeflossen, bei denen die Einwilligung in die Datenverarbeitung erteilt wurde, und die vollständig ausgefüllt wurden (d.h. die zuletzt gestellte Frage war Frage 48 oder 49). Die bereinigten, gefilterten und anonymisierten Daten wurden mit R analysiert und mit [R Plotly](https://plotly.com/r/) in interaktiven Charts visualisiert. Der Bericht wurde mit [R bookdown](https://bookdown.org/yihui/bookdown/) generiert und auf dem QUEST Center-Server für Web-Apps veröffentlicht. Der der Analyse zugrundeliegende Code wurde auf [GitHub](https://github.com/quest-bih/bua-rdm-survey) und [Zenodo](https://doi.org/10.5281/zenodo.7061742) veröffentlicht.

</div>
